; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.extra_flags = -DBOARD_HAS_PSRAM

monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
monitor_filters =
	time
	colorize
	esp32_exception_decoder

#define WIFI_SSID     "TP-Link_E3AC"
#define WIFI_PASSWORD "I&Mmansion2021"      // WiFi password exposed
#define TG_BOT_TOKEN  "8896687319:AAGYa5..."  // Telegram bot token exposed